version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
   
  test-db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
      ports:
        - '5433:5432'
      volumes:
        - test_pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  test_pgdata: